apiVersion: v1
kind: Service
metadata:
  name: kube-green-kafka
  namespace: kube-green
spec:
  type: ClusterIP
  selector:
    app: kube-green-kafka
  ports:
  - port: 9092
    name: client
  clusterIP: 10.102.211.222
