apiVersion: v1
kind: Service
metadata:
  name: kube-green-kafka-manager
  namespace: kube-green
spec:
  type: NodePort
  selector:
    app: kube-green-kafka-manager
  ports:
  - port: 9000
    nodePort: 30033
    targetPort: 9000
    protocol: TCP

